### ISSUE TITLE
Critical Exception: Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by grufkork** [EtiTheSpirit/BNKReplacer#6]
Hello! I was just trying out this tool with BPM: Bullets Per Minute when I got this error. Main.bnk is almost 2GB, and BPM is built with UE 4.25.3.0. It happens both with multiple, one and no songs in ConversionMap.txt. Honestly, I'm very much in the dark here so I'm not sure what more would help telling :P

Main2.bnk shows up, but it contains no data.

```
Enter the path to the source file (the file that you want to modify).
Do not put quotes around the path.
E:\gameLibraries\SteamLibrary\steamapps\common\BPM BULLETS PER MINUTE\WindowsNoEditor\BPM\Content\Paks\unpacked\BPM\Content\WwiseAudio\Windows\Main.bnk
Enter the path to the destination file (the file that will contain your edits).
Do not put quotes around the path.
E:\gameLibraries\SteamLibrary\steamapps\common\BPM BULLETS PER MINUTE\WindowsNoEditor\BPM\Content\Paks\unpacked\BPM\Content\WwiseAudio\Windows\Main2.bnk
REVIEW YOUR DATA: You want to make the following replacements...
File ID [73148963]   => [Explicit Conversion] PSA.mp3
(n.b. Implicit means that you didn't put anything after the ID and the program is guessing which file you want the ID to correspond to.)
Is this data correct? [y/N]
Sit back and chillax. The program's doing its thing...
Reading file...
>> Skimming Section BKHD... (This section is not necessary for BNK patching)
Done populating BNK file.
Shit hit the fan! A critical exception was thrown. Here's the error: Arithmetic operation resulted in an overflow.
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LazyBNKFormat.BNKFile..ctor(Stream inputFile)
   at NMSBNKPatcher.BNKPatcher..ctor(Stream bnkFile)
   at NMSBnkRepacker.Repacker.FakeMain(String[] args)
   at NMSBnkRepacker.Repacker.Main(String[] args)
Press enter to quit...

**Comment by EtiTheSpirit** [comment]
Looks like the file is just too big to handle. I'm not sure if it's something I can fix seeing that the error is thrown in a system library.
